### ISSUE TITLE
Morning session: peer-to-peer code review

### ISSUE THREAD

**Issue by adel-gu** [adel-gu/Portfolio#7]
### Project requirements 🏗:

- Building the contact form in the footer: 
   - All fields must have placeholder text.

### The Final product: 
![footer-section](https://user-images.githubusercontent.com/68030297/186596150-d227ec81-d7e8-4fca-8f4c-62082345e4ee.png)

### Current working project: 
![image](https://user-images.githubusercontent.com/68030297/186595221-38306659-efcb-4706-a3bf-f5f2ea11d84f.png)

### Challenges: 
- One of the main challenges is:
   - Is the text where those red arrows pointing at a **placeholder** Attribute or a **label** element?
   - In case of that text is **placeholders**, how would you style that in `CSS`.

### Last tow commits in this project: 
- [rearrange footer section order](https://github.com/adel-gu/portfolio-mobile-first/pull/6/commits/e848e43a2e1e7645b87b75cc9cb1b6b94410d3e9)
- [update footer content and add classes](https://github.com/adel-gu/portfolio-mobile-first/pull/6/commits/bbf6ba3ee4e64c60ca2ae884b05f3d8655cef18e)

**Comment by AhmedNazirMusah** [comment]
https://github.com/adel-gu/portfolio-mobile-first/blob/f86d641083707a5d4b4108d16426f55ec99c0565/index.html#L280-L290

Well arranged and clean...nicely done.

**Comment by MaiRizk** [comment]
Great job so far. 
Regarding the issue you're facing, you can give the label position absolute and position it accordingly.

**Comment by SelmaNdapanda** [comment]
I suggest you need to add the interactions to the placeholders. The placeholder must originally be in the middle, but once you hover over it, it must float towards the top and decrease their sizes so they create space for the input.

**Comment by adel-gu** [comment]
@SelmaNdapanda, @AhmedNazirMusah, and @MaiRizk appreciate that thank you all🙌
